[package]
name = "data_types"
version = "0.1.0"
authors = ["Jefferson M Fujioka <j.fujioka@dac.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://crates.io/crates/rand
rand = "0.7.3"