[package]
name = "hello_world"
version = "0.0.0"
authors = ["Jefferson M Fujioka <jefferson.fujioka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
